### PR TITLE
fix plot window scaling

### PR DESCRIPTION
**Pull request by milesfrain**

### CODE REVIEW

**Comment by pfitzseb** [comment]
Is this necessary with https://github.com/JuliaPlots/Plots.jl/pull/2196?

**Comment by milesfrain** [comment]
A few changes are needed. Writing up a summary in https://github.com/JunoLab/Juno.jl/issues/353

**Comment by pfitzseb** [comment]
I'm not sure I'm comfortable with this solution -- you'll end up getting way too small Plots whenever the plotting backend doesn't respect our `devicePixelRatio` info.
An alternative would be to set the initial `scale` such that the whole plot is visible (maybe with an upper bound at 1 so as to not cause blurriness for small plots). Thoughts?

**Comment by milesfrain** [comment]
Fair point.
A whole-plot-visible strategy would also work well.
Does `canopy.jl` have access to the plot image width and height? I'd need to take a deeper dive to figure out which dimensions refer to either:
* Plot pane pixels
* Plot view coordinates (e.g. zoom into a 10x10 box at position 50,50 of the larger plot)
* Original plot image pixels

If you have an implementation in-mind, I'd also be happy to test it out. Doing the research described above is lower on my priority list this week.

**Pull request closed without merging**
