### PR TITLE
Allow multiple plots in plotpane

### PR DESCRIPTION
**Pull request by pfitzseb**
multiplots

### CODE REVIEW

**Comment by MikeInnes** [comment]
Awesome!

Unrelated, but at one point @shashi made a nice Juno plot theme (maybe it was just for Gadfly). Would be cool to get that working with Plots.

**Comment by pfitzseb** [comment]
https://github.com/JuliaPlots/PlotThemes.jl/pull/26

**Comment by MikeInnes** [comment]
Cool, way ahead of me as always.

**Comment by shashi** [comment]
Nice theme!

**Pull request merged**
