### PR TITLE
Performance improvements for result animations

### LINKED ISSUE #441: [BUG] 10% Idle CPU with Ink enabled on Ubuntu 19.10
Hi,

top reports a 10% CPU usage when idling. This only stops after I disable the Ink package and restart Atom.

## Details
- Atom version: 1.41.0
- Julia version: 1.3.0
- OS: Ubuntu 19.10 (x64, latest updates)
- Package versions:
  - Atom.jl: 0.11.3
  - julia-client: 0.11.3
  - ink: 0.11.7

### Steps to reproduce

1. Start Atom
2. Start top
3. Realize that top shows 10% CPU for Atom 

How can I debug this? Are there any logs to look for suspicious entries?

### PR DESCRIPTION
**Pull request by pfitzseb**
and breakpoint gutter insertion.

Fixes https://github.com/JunoLab/Juno.jl/issues/441.

This brings the typical idle CPU load without any results down to ~2% for me, which is *much* better than before.

### CODE REVIEW

**Comment by laborg** [comment]
Thank you for this!

**Comment by ssfrr** [comment]
Would you mind tagging a release with this improvement? I was just digging into some of this idle CPU usage myself and saw that it had already been reported and fixed! Thanks again for all your great work on Juno.

**Comment by pfitzseb** [comment]
Whoops, didn't realize I was this far behind in tagging packages. [0.11.8](https://github.com/JunoLab/atom-ink/releases/tag/v0.11.8) includes this fix and a bunch of other improvements.

**Comment by ssfrr** [comment]
Great, thanks.

**Pull request merged**
