### PR TITLE
option for ctrl/cmd modifier when clicking link

### PR DESCRIPTION
**Pull request by pfitzseb**

### CODE REVIEW

**Comment by aviatesk** [comment]
As far as I understand, those PRs force us to use explicity ctrl/cmd key pressing for opening links and preventing "just clicking on links" from opening links ?

**Comment by pfitzseb** [comment]
Yup. I got annoyed when I just wanted to click on the REPL to move focus there and instead ended up in an editor again because I hit a link by accident.

**Comment by kragol** [comment]
Maybe there could be something like a popup helping users discover the new behaviour, at least the first time? Or maybe not making the new behaviour the default?

For the story, I just had a very poor experience with this after upgrading from an older version of juno. Since it looked like a regression I spent hours trying to find the guilty update, alternatively downgrading atom, reinstalling packages, downgrading packages until I found it was related to the julia-client 0.12.0 update. It is only then that I found it was mentioned in the release notes on the discourse post (which wouldn't have been that easy to find if I did not actually see it a like a week ago).

Anyway, I am not here to rant and I am very grateful for your awesome work. I just wanted to maybe spare other users the silly hunt I just went through.

**Comment by aviatesk** [comment]
@kragol we have the issue for what you want [here](https://github.com/JunoLab/Juno.jl/issues/508)

**Comment by kragol** [comment]
Thanks, I missed that one. It's not entirely clear to me where issues are or should be reported, whether it's on ink, julia-client, juno, etc. Do you have any guidelines for that?

**Comment by pfitzseb** [comment]
You should get pointed to Juno.jl whenever you try to open a new issue on any of those repos:
image

**Comment by kragol** [comment]
OK thanks for the clarification.

**Pull request merged**
