### PR TITLE
Provide description

### PR DESCRIPTION
**Pull request by rgbkrk**
When searching for this package, I noticed it didn't have a description filled out. I realize you're aiming to be a generic IDE toolkit, I just wrote Julia for now since that's the one that's implemented now.

### CODE REVIEW

**Comment by MikeInnes** [comment]
Thanks for the patch – I think it would be best not to make it Julia specific though, especially since the proto-repl plugin for clojure now uses ink as well.

**Comment by owend** [comment]
I noticed this too (had to check the url to make sure it was the right package)  What about the first line in the readme?  "Ink is a toolkit for building IDEs in Atom"

**Comment by rgbkrk** [comment]
Done.

**Comment by MikeInnes** [comment]
Looks good, thanks!

**Pull request merged**
