### PR TITLE
limit number of items in plot history

### PR DESCRIPTION
**Pull request by pfitzseb**

### CODE REVIEW

**Comment by BeastyBlacksmith** [comment]
is that the total number of plots in history? Or the number of plots currently in RAM and others will be loaded on demand?
I ask, because I frequently plot ~200 plots.

**Comment by pfitzseb** [comment]
Total number. Are you actually navigating through all 200 plots?

**Comment by BeastyBlacksmith** [comment]
I do. That is an average number of solutions for a trajectory and then I scroll through the plots to see how things evolve. I would vote to have this as a user-setting.

**Comment by pfitzseb** [comment]
Fair enough, I can do that.

**Pull request merged**
