### PR TITLE
ES6 / Etch

### PR DESCRIPTION
**Pull request by MikeInnes**
I’m using this PR to experiment with [etch](https://github.com/atom/etch), which potentially solves some of our issues creating ad-hoc views everywhere.

The workspace seems like a good fit for this since it’ll be nice not to reset the view on every update.

Anyone have any opinions on ES6 vs CoffeeScript? I somewhat dislike ES6’s verbosity but could get used to it.

### CODE REVIEW

**Comment by MikeInnes** [comment]
Now that the workspace is ported, some more thoughts:
- I like ES6 more than I thought I would, and I'm looking forward to working with JSX and async syntax more. A more traditional syntax may be better for contributions too.
- The etch/reactive model is also really nice.
- ES6 is a bit fiddlier and verboser – we'll probably need some linting to avoid common pitfalls.
- Not having atom-eval puts a serious dent in my workflow, but I think I can implement hot-reloading to fix this.
- This PR brings a slight LoC bump but I think that's pure `{`s – the actual lines of code and complexity are already a lot less and that's before we start stripping out our custom view code.

So overall I'm pretty sold on this, but would like to hear others' thoughts as well.

**Comment by pfitzseb** [comment]
This looks pretty nice, I like it!

I mean, I like coffeescript a lot, but ES6 doesn't seem to be as ugly as ES5 in many regards. We should be able to set CI up for linting, Atom core has that as well (though linting locally might be sufficient for now).

etch seems great, we should defintely use it. Not quite sure why this works as is though, does Atom do the babel transpiling and stuff whenever it encounters the `'use babel'` pragma and that's it?

Anyways, I'd be in favour of writing new code is ES6 and rewriting the old modules whenever we have the time (similar to Atom core).

**Comment by MikeInnes** [comment]
Yup, just auto detects it and compiles exactly as with coffeescript.

I had a go at moving progress bars to etch (not complete yet) and you can see how much dramatically simpler it is with etch vs our old event handler approach. I think this'll help a lot with more complex views.

I agree that the transition should be fairly organic. I've been using [this](https://github.com/decaffeinate/decaffeinate) which makes the first pass just a small cleanup. Converting anything that doesn't have a view, when we want to, should be pretty trivial.

**Comment by pfitzseb** [comment]
Yeah, it's crazy how much simpler the view stuff is with etch. Love it.

**Comment by MikeInnes** [comment]
Closing this PR as it's gotten way out of hand – will pull commits off of my dev branch for review.

**Pull request closed without merging**
