### PR TITLE
remove stuff

### PR DESCRIPTION
**Pull request by aviatesk**

### CODE REVIEW

**Comment by aviatesk** [comment]
whoop 1000 lines.
hope this makes loading time better even small

**Comment by pfitzseb** [comment]
Yeah, feels good to get rid of the legacy console ;)

**Comment by jebej** [comment]
I liked the legacy console :( it allowed you to edit text with the mouse and on multiple lines

**Comment by jebej** [comment]
and all of the cool stuff from the readme:

**Pull request merged**
