### PR TITLE
Add ANSI codes on stdout and stderr

### PR DESCRIPTION
**Pull request by mauricioszabo**
I'm working with Clojure, with proto-repl. When I work with midje and other test libraries that colorize outputs, my text becomes **very** garbled and sometimes I'm not even able to find out what's wrong.

(before)
image

This PR adds a new dependency (because ANSI parsing is kinda hard) and wire it to stdout and stderr, so the same colors that would appear on terminal will appear in the console:

(after)
image

### CODE REVIEW

**Comment by MikeInnes** [comment]
I was going to point out that this seems like a library issue, where they should be trying to detect whether a colour terminal is available or not. But this is a very sensible solution so it's hard to say no :) LGTM!

**Comment by pfitzseb** [comment]
Can you rebase this on latest master? I think I introduced some conflict somewhere...
Thanks!

**Comment by mauricioszabo** [comment]
Okay, I've merged it. It was just a `require`.

**Comment by pfitzseb** [comment]
Great, thanks!

**Comment by alza-bitz** [comment]
Any chance of releasing a new version with this feature included? I see it just missed the last cut. Thanks!

**Comment by alza-bitz** [comment]
Hi there, 

I noticed that ANSI colors were suddenly working when I updated atom-ink :)

Thanks for making a new release!

**Comment by pfitzseb** [comment]
Heh, great to hear they still work -- wasn't sure I hadn't broken them some time back...

**Pull request merged**
